Implement Town::update at 0x0049742F
OpenLoco/OpenLoco pull request #1220
Opened 2021-10-16 16:03 UTC by petergaal

2021-11-12 11:09 UTC, AaronVanGeffen requested changes
Apologies for the delay in testing this.

Unfortunately, replay tests fail on the [Randomland by matsku84 - 2050.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/7527061/Randomland.by.matsku84.-.2050.SV5.zip) save. Leave the game running for an in-game month to see a divergence in the autosave, compared to doing the same thing on master.

Local comparison for the second autosave generated using Beyond Compare:
```
Hex Compare
Produced: 12/11/21 12:09:33 pm 

Left file: /home/aaron/Repositories/OpenLoco/OpenLoco/build/config/save/autosave/matsku-2050-master-compressed-post-1101/autosave_2021-08-12_13-46-41.SV5
Right file: /home/aaron/Repositories/OpenLoco/OpenLoco/build/config/save/autosave/autosave_2021-11-12_12-05-47.SV5
2248645 same byte(s)
5305 left orphan byte(s)
5306 right orphan byte(s)
8686 difference byte(s)
```

2021-11-14 21:31 UTC, duncanspumpkin commented on src/OpenLoco/Town.cpp
> +        if (buildSpeed == 0 || (buildSpeed == 1 && (gPrng().randNext() & 7) == 0))
this should be `buildSpeed == 0 || (buildSpeed == 1 && (gPrng().randNext() & 7))`

2021-11-14 21:33 UTC, duncanspumpkin commented
Can you recheck this @AaronVanGeffen

2022-01-17 16:24 UTC, duncanspumpkin commented
Confirmed no divergence against master.

2022-01-17 16:26 UTC, merged