Implement Company::aiThink
OpenLoco/OpenLoco pull request #1235
Opened 2021-10-24 20:08 UTC by ZehMatt

2021-11-12 11:25 UTC, AaronVanGeffen reviewed
Apologies for the radio silence on testing this. I wonder what a good approach would be? There are calls to prng functions involved, and OpenLoco's prng implementation differs from vanilla. That rules out our usual batch of replay tests, unfortunately.

2021-11-12 17:15 UTC, ZehMatt commented
> Apologies for the radio silence on testing this. I wonder what a good approach would be? There are calls to prng functions involved, and OpenLoco's prng implementation differs from vanilla. That rules out our usual batch of replay tests, unfortunately.

How/Why is the prng different? And if thats the case cant we make new ones with the new prng state.

2021-11-12 18:35 UTC, duncanspumpkin commented
There are like 3 slight variations that cs used in locomotion. We only implemented one variation so if the code you implemented doesn't match that variation it will be different.

2021-11-12 22:17 UTC, ZehMatt commented
> There are like 3 slight variations that cs used in locomotion. We only implemented one variation so if the code you implemented doesn't match that variation it will be different.

Would have been probably not a bad idea to have all 3 generator functions before turning them into one.

2021-11-14 21:37 UTC, duncanspumpkin commented
This function is using the same gprng code as vanilla so it should match on a replay.

2021-11-14 21:41 UTC, duncanspumpkin commented on src/OpenLoco/Company.cpp
> +        if (headquarters_x == -1 && (challenge_flags & CompanyFlags::bankrupt) == 0 && (challenge_flags & 0x1) != 0)
suggest inverting this and returning early.

2021-11-14 21:42 UTC, duncanspumpkin commented on src/OpenLoco/Company.cpp
> +        if (headquarters_x == -1 && (challenge_flags & CompanyFlags::bankrupt) == 0 && (challenge_flags & 0x1) != 0)
Add a defintion in the CompanyFlags table for (1<<0)

2021-11-14 21:46 UTC, duncanspumpkin commented on src/OpenLoco/Company.cpp
> +            const auto selectedPos = randPos - Map::Pos2{ 512, 512 } + pos;
I think making this `- Map::TilePos2{ 16, 16 }` would be more easy to read. Also Suggest moving the first sum into the randPos so it makes it obvious that the rand is +- 16 tiles.

2021-11-14 21:48 UTC, duncanspumpkin commented on src/OpenLoco/Company.cpp
> +            if (selectedPos.x <= 0x2FFF && selectedPos.y <= 0x2FFF)
`Map::validCoords`

2021-11-14 21:52 UTC, duncanspumpkin commented on src/OpenLoco/Company.cpp
> +                coord_t z = surface->baseZ() << 2;
* 4

2021-11-14 21:53 UTC, duncanspumpkin commented on src/OpenLoco/Company.cpp
> +                const auto rot = randPos.y & 3;
This wont work. randPos.y has been &0x3E0. You need to get the rand out of `randPick`.
rot = (Utility::ror<uint32_t>(randPick, 10)) & 0x3;

2021-11-14 21:55 UTC, duncanspumpkin requested changes
see comments

2022-01-20 08:07 UTC, duncanspumpkin commented
No divergence after 1000 ticks

2022-01-20 08:07 UTC, duncanspumpkin approved these changes

2022-01-20 12:21 UTC, merged