Implement further objFuncs
OpenLoco/OpenLoco pull request #1423
Opened 2022-04-02 08:29 UTC by duncanspumpkin

2022-04-03 07:28 UTC, duncanspumpkin commented on src/OpenLoco/Objects/TrackObject.h
> +        uint16_t var_0E;        // ?compatible signals bitset?
possible source of a bug here as we were accessing this incorrectly as uint8_t

2022-04-15 14:50 UTC, LeftofZen commented
Testing this branch, I get an interop crash on game startup, trying to narrow down the source now

2022-04-15 14:54 UTC, duncanspumpkin commented on src/OpenLoco/Objects/TrackObject.cpp
> +        Interop::call(0x0042F4D0, regs);
Missmatch between function call and offset address...

2022-04-19 23:34 UTC, LeftofZen requested changes
Merge conflicts

2022-05-26 01:01 UTC, LeftofZen approved these changes
tested on a few maps/games, couldn't find any issues with it

2022-05-26 05:48 UTC, merged