Implement vehiclePickupAir game command
OpenLoco/OpenLoco pull request #2025
Opened 2023-07-10 17:42 UTC by AaronVanGeffen

2023-07-12 18:20 UTC, duncanspumpkin commented on src/OpenLoco/src/Windows/Vehicle.cpp
> +                    auto flags = GameCommands::Flags::apply | GameCommands::Flags::flag_3 | GameCommands::Flags::flag_6;
should be just apply. Flags were incorrect before.

2023-07-12 18:20 UTC, duncanspumpkin commented on src/OpenLoco/src/Windows/Vehicle.cpp
> +                    auto flags = GameCommands::Flags::apply | GameCommands::Flags::flag_3 | GameCommands::Flags::flag_6;
same here.

2023-07-12 18:27 UTC, duncanspumpkin commented on src/OpenLoco/src/GameCommands/VehiclePickupAir.cpp
> +        regs.ebx = vehiclePickupAir(EntityId(regs.di), regs.bl);
Use the args to handle the deserialisation.

2023-07-12 18:28 UTC, duncanspumpkin requested changes
See comments some minor changes/fixes

2023-07-12 18:57 UTC, AaronVanGeffen commented on src/OpenLoco/src/GameCommands/VehiclePickupAir.cpp
> +                station->airportMovementOccupiedEdges &= ~(1 << train.head->airportMovementEdge);
```suggestion
                station->airportMovementOccupiedEdges &= ~(1ULL << train.head->airportMovementEdge);
```

2023-07-15 20:37 UTC, duncanspumpkin approved these changes

2023-07-15 20:53 UTC, merged