Signal/Level Crossing Animation Update
OpenLoco/OpenLoco pull request #2536
Opened 2024-07-16 19:14 UTC by duncanspumpkin

The remaining two animation updates

2024-07-17 09:50 UTC, LeftofZen commented on src/OpenLoco/src/Objects/LevelCrossingObject.h
> +        uint8_t var_0A;         // 0x0A
my favourite question - do you have any ideas for names/what these variables do? also `unk2` in the  enum below

2024-07-17 09:57 UTC, LeftofZen requested changes
The signals appear to function correctly but some signals do not visually update. The semaphore ones do update visually/animate, but the tricolour/modern ones (called "Colourlight" ingame) do not update visually at all.

2024-07-18 00:48 UTC, LeftofZen commented on src/OpenLoco/src/Objects/LevelCrossingObject.h
> +        uint8_t var_0A;         // 0x0A
also is there a var_0B or is that padding? or is 0A uint16?

2024-07-18 01:26 UTC, LeftofZen commented on src/OpenLoco/src/Objects/LevelCrossingObject.h
> +        uint8_t pad_0C;
this is 0x0B

2024-07-18 01:43 UTC, LeftofZen requested changes
variable is 0x0B, not  0C

2024-07-18 06:07 UTC, duncanspumpkin commented on src/OpenLoco/src/Objects/LevelCrossingObject.h
> +        uint8_t pad_0C;
Good catch

2024-07-18 08:26 UTC, duncanspumpkin commented
> The signals appear to function correctly but some signals do not visually update. The semaphore ones do update visually/animate, but the tricolour/modern ones (called "Colourlight" ingame) do not update visually at all.

think i've fixed that now

2024-07-21 11:57 UTC, LeftofZen approved these changes

2024-07-21 11:57 UTC, LeftofZen commented
> > The signals appear to function correctly but some signals do not visually update. The semaphore ones do update visually/animate, but the tricolour/modern ones (called "Colourlight" ingame) do not update visually at all.
> 
> think i've fixed that now

yep looks good to me

2024-07-21 12:21 UTC, merged