Hide scrollbars when there is nothing to scroll
OpenLoco/OpenLoco pull request #2578
Opened 2024-08-07 13:00 UTC by AaronVanGeffen

This PR changes the scrollview behaviour such that scrollbars are no longer drawn when the scrollview contents do not overflow the visible area.

Basically the same as https://github.com/OpenRCT2/OpenRCT2/pull/22491

2024-08-10 02:26 UTC, LeftofZen requested changes
The scrollbar flickers when you resize the window horizontally. Might also need to check OpenRCT2 for this if the implementation is the same

https://github.com/user-attachments/assets/75502fa8-32ba-421c-8fe2-ecdacdfdfa7e

2024-08-10 08:02 UTC, AaronVanGeffen commented
Thanks for testing. I hadn't observed this myself, so I'm glad you caught it. Wonder what's causing it.

2024-08-13 18:47 UTC, AaronVanGeffen commented
After much debugging, I found the bug in `Input::stateResizing`. It's annoyingly simple:
```diff
--- a/src/OpenLoco/src/Input/MouseInput.cpp
+++ b/src/OpenLoco/src/Input/MouseInput.cpp
@@ -790,7 +790,7 @@ namespace OpenLoco::Input
         w->scrollAreas[0].contentHeight = -1;
         w->scrollAreas[1].contentWidth = -1;
         w->scrollAreas[1].contentHeight = -1;
-        window->updateScrollWidgets();
+        w->updateScrollWidgets();
         w->invalidate();

         _dragLastX = x;
```

2024-08-13 22:35 UTC, LeftofZen approved these changes
flickering scrollbar is now gone and everything works nicely. there are a few small pixel-perfect issues with the window still being scrollable even if the scrollbar has disappeared (i think the scrollbar just disappears a couple of pixels too soon) but it isn't enough to iterate on, imo

2024-08-14 07:04 UTC, duncanspumpkin approved these changes

2024-08-14 07:55 UTC, merged