Fix track/trackAddition paint issues
OpenLoco/OpenLoco pull request #2658
Opened 2024-10-15 07:27 UTC by duncanspumpkin

Most of #2655

2024-10-15 07:38 UTC, duncanspumpkin commented on src/OpenLoco/src/Paint/Paint.cpp
> +                    minMaxBounds.x = std::min(minMaxBounds.x, child->bounds.x);
i don't know why i thought it would be max for this it doesn't even pass basic principles as to what you would expect.

2024-10-15 08:12 UTC, LeftofZen approved these changes
This does appear to resolve the diagonal track issues:

![image](https://github.com/user-attachments/assets/b2688c9b-9b96-4cad-add2-95f9a9bb6cf5)

2024-10-15 08:17 UTC, LeftofZen commented
Also confirming that this also fixes the "no bogey on train" issue (image 4), as that also occurred on the diagonal track

2024-10-15 08:20 UTC, LeftofZen commented
Fixes #2540

2024-10-15 08:21 UTC, LeftofZen requested changes
I forgot, this will need a changelog

2024-10-18 09:03 UTC, AaronVanGeffen approved these changes

2024-10-18 09:11 UTC, merged

2024-11-17 13:26 UTC, LeftofZen commented
Fixes #2540