Vehicle update2 Part 1: Water Update
OpenLoco/OpenLoco pull request #738
Opened 2021-02-07 19:10 UTC by duncanspumpkin

Implements vehicle_head Update up to the Water update function.

2021-02-07 19:19 UTC, AaronVanGeffen commented
Really nice to see some work on these vehicle functions again.

I notice `Vehicle.cpp` is declaring `using namespace OpenLoco`. I think instead its contents should be _in_ `namespace OpenLoco`, or perhaps even `OpenLoco::Vehicle`?

2021-02-09 19:59 UTC, duncanspumpkin commented
Okay think thats all I will do in this PR. I'll not be adding any more to this one.

2021-02-11 08:45 UTC, duncanspumpkin commented on src/OpenLoco/Vehicles/VehicleHead.cpp
> +    void VehicleHead::updateTrainSounds()
Update driving sounds. Need to differentiate it from start movement sounds.

2021-02-12 16:21 UTC, AaronVanGeffen commented
On this PR's branch, boats no longer have wakes. They are rendered correctly on current master.

2021-02-12 16:21 UTC, AaronVanGeffen requested changes
As of this PR, boats no longer have wakes. They are rendered correctly on current master.

2021-02-12 18:24 UTC, AaronVanGeffen commented
Okay, here's how I went about testing the waters. I let the game run on a very busy save for a two in-game months, autosaving every month. I first compared two runs of this branch to itself. The results are fairly deterministic, save for a few bytes. I then did the same thing on master. Again, the results are were deterministic. Finally, I compared the autosaves from one branch to the other. I am elated to say this is yielding positive results.

#### This branch:
```
# First month, session 1 vs session 2
$ diff <(xxd autosave_2021-02-12_17-55-51.SV5) <(xxd autosave_2021-02-12_17-56-15.SV5) | wc -l
16
# Second month, session 1 vs session 2
$ diff <(xxd autosave_2021-02-12_17-55-40.SV5) <(xxd autosave_2021-02-12_17-56-04.SV5) | wc -l
16
```

#### master:
```
# First month, session 1 vs session 2
$ diff <(xxd master/autosave_2021-02-12_19-16-11.SV5) <(xxd master/autosave_2021-02-12_19-16-33.SV5) | wc -l
12
# Second month, session 1 vs session 2
$ diff <(xxd master/autosave_2021-02-12_19-16-23.SV5) <(xxd master/autosave_2021-02-12_19-16-44.SV5) | wc -l
16
```

#### master vs this branch:
```
# First month (this branch vs master)
$ diff <(xxd duncan/autosave_2021-02-12_17-56-04.SV5) <(xxd master/autosave_2021-02-12_19-16-33.SV5) | wc -l
16
# Second month (this branch vs master)
$ diff <(xxd duncan/autosave_2021-02-12_17-56-15.SV5) <(xxd master/autosave_2021-02-12_19-16-44.SV5) | wc -l
16
```


#### For completeness, example output:
```
$ diff <(xxd duncan/autosave_2021-02-12_17-56-15.SV5) <(xxd master/autosave_2021-02-12_19-16-44.SV5)
27895c27895
< 0006cf60: 6500 cf00 bd68 76ff 0008 2306 002e 03c0  e....hv...#.....
---
> 0006cf60: 6500 c800 bd68 76ff 0008 2306 002e 03c0  e....hv...#.....
27914c27914
< 0006d090: a897 8604 020d bc00 0180 f0fa 02a8 61ff  ..............a.
---
> 0006d090: a897 8604 0207 bc00 0180 f0fa 02a8 61ff  ..............a.
27977c27977
< 0006d480: 59b9 8700 e803 0100 1412 0003 0003 0003  Y...............
---
> 0006d480: 52b9 8700 e803 0100 1412 0003 0003 0003  R...............
172909c172909
< 002a36c0: 0087 fd07 0002 6775 1913                 ......gu..
---
> 002a36c0: 0087 fd07 0002 5375 1913                 ......Su..
```

2021-02-12 18:25 UTC, AaronVanGeffen approved these changes

2021-02-12 18:37 UTC, merged