Fix waypoint setting function
OpenLoco/OpenLoco pull request #797
Opened 2021-02-26 19:54 UTC by duncanspumpkin

Calculation was incorrectly adding the offset to the first tile instead of removeing the offset from the current tile. This meant that it would set the waypoint at the wrong location

2021-02-26 20:06 UTC, AaronVanGeffen commented
How would we best go about testing this?

Perhaps we can share a CI build for testing with the users who reported the issue?

2021-02-26 20:19 UTC, duncanspumpkin commented
its immediately obvious when you try set a waypoint on curved track the waypoint changes position depending on where you clicked on the track. What is meant to happen is the waypoint is always at the first tile of the curve.

2021-02-27 07:46 UTC, senner007 commented
@AaronVanGeffen 
Can it not be set to automatically create a windows executable for each pr?

2021-02-27 07:50 UTC, AaronVanGeffen commented
@senner007 It already does. You can find the CI artefacts in the Checks tab for this PR, for example. Unfortunately, this isn't very discoverable for most users.

2021-02-27 07:54 UTC, senner007 commented
@AaronVanGeffen 
Yes I see

2021-02-27 09:04 UTC, senner007 commented
This does not fix #798

2021-02-27 09:25 UTC, AaronVanGeffen commented
@senner007 The bug is in setting the waypoints. Did you remove and set the waypoints again? Otherwise, the bad waypoint will persist.

2021-02-27 09:32 UTC, senner007 commented
> @senner007 The bug is in setting the waypoints. Did you remove and set the waypoints again? Otherwise, the bad waypoint will persist.

Yes I did that. Could this be an original bug?

2021-02-27 10:49 UTC, AaronVanGeffen commented on CHANGELOG.md
> +- Fix: [#798] Setting waypoints on multitile track/road elements corrupt the position.
```suggestion
- Fix: [#798] Setting waypoints on multitile track/road elements corrupts the position.
```

2021-02-27 11:23 UTC, duncanspumpkin commented
There's two issues with waypoints one is that people feel they are ignored the other was that setting them on multi tile tracks wasn't working. This corrects the second issue

2021-02-27 14:39 UTC, AaronVanGeffen requested changes
Unfortunately, I can confirm the issue is not fully fixed. Both straight parts and curved parts still seem to be iffy.

Here's my test save from v21.02: [Test2.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/6054631/Test2.SV5.zip)
And re-routed using this PR: [Test3.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/6054632/Test3.SV5.zip)

2021-02-28 12:09 UTC, AaronVanGeffen commented on src/OpenLoco/Vehicles/Orders.cpp
> +        _data[3] |= (trackId & 0x1F) << 3;
Nice catch!

2021-02-28 12:16 UTC, AaronVanGeffen approved these changes

2021-02-28 12:16 UTC, senner007 commented on src/OpenLoco/Vehicles/Orders.cpp
> +        _data[3] |= (trackId & 0x1F) << 3;
Yes. #798 fixed

2021-02-28 12:19 UTC, merged